name: meu_hiit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8
  mobx_codegen: ^2.0.7
  modular_test: ^2.0.0
  build_runner: ^2.1.10


flutter_native_splash:
    background_image: "assets/images/splash_screen.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
